/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.TTBangDiemBL;
import BLL.TTHOCSINHBL;
import DAL.TTBangDiem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thái Dương
 */
public class FormBangDiemHocSinh extends javax.swing.JFrame {

    /**
     * Creates new form FormBangDiemHocSinh
     */
    public FormBangDiemHocSinh() {
        initComponents();
        initStudent();
        ProcessCrt(false);
    }
ArrayList<TTBangDiem> arr =  new ArrayList<TTBangDiem>();
    DefaultTableModel model;
    public void initStudent()
        {
            List<TTBangDiem> listSV;
            listSV = TTBangDiemBL.dsBangDiem();
            if(listSV.size()>0)
        {
            model = (DefaultTableModel)Tbl_Bangdiem.getModel();
            for(TTBangDiem s:listSV) 
        {
            String hocluc = "";
            if (s.getfDiemTB() >= 8) {
                hocluc = "Giỏi";
            } else if (s.getfDiemTB() >=  6.5) {
                hocluc = "Khá";
            } else if (s.getfDiemTB() >= 5) {
                hocluc = "Trung bình";
            } else if (s.getfDiemTB() >= 3.5) {
                hocluc = "Yếu";
            } else {
                hocluc = "Kém";
            }
            model.addRow(new 
            Object[]{s.getStrMaBD(),s.getStrMahs(),s.getStrTenhs(),s.getStrLop(),s.getStrMaMH(),s.getfDiemTB(),hocluc, s.getStrManvString()});
        }
    } 
 }
    
    public void ProcessCrt(boolean b)
{
    this.Btn_Them.setEnabled(b);
    this.Btn_Sua.setEnabled(b);
    this.Btn_Xoa.setEnabled(b);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txt_Mabd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_DiemTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_Mahs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_hocluc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_Tenhs = new javax.swing.JTextField();
        Txt_Manv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Bangdiem = new javax.swing.JTable();
        Btn_Them = new javax.swing.JButton();
        Btn_Sua = new javax.swing.JButton();
        Btn_Xoa = new javax.swing.JButton();
        Btn_tieptuc = new javax.swing.JButton();
        Btn_quaylai = new javax.swing.JButton();
        Txt_malop = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_Mamh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("QUẢN LÝ BẢNG ĐIỂM");

        jLabel1.setText("Mã bảng điểm:");

        jLabel3.setText("Điểm trung bình:");

        jLabel4.setText("Mã học sinh:");

        jLabel5.setText("Học lực:");

        jLabel6.setText("Tên học sinh:");

        jLabel7.setText("Mã nhân viên:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("DANH SÁCH THÔNG TIN BẢNG ĐIỂM");

        Tbl_Bangdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bảng điểm", "Mã Học sinh", "Tên học sinh", "Lớp", "Mã môn học", "Điểm", "Học lực", "Mã nhân viên"
            }
        ));
        Tbl_Bangdiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_BangdiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Bangdiem);

        Btn_Them.setBackground(new java.awt.Color(51, 255, 51));
        Btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Them.setText("THÊM");
        Btn_Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ThemActionPerformed(evt);
            }
        });

        Btn_Sua.setBackground(new java.awt.Color(255, 153, 51));
        Btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Sua.setText("SỬA");
        Btn_Sua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SuaActionPerformed(evt);
            }
        });

        Btn_Xoa.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Xoa.setText("XÓA");
        Btn_Xoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XoaActionPerformed(evt);
            }
        });

        Btn_tieptuc.setBackground(new java.awt.Color(255, 153, 153));
        Btn_tieptuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_tieptuc.setForeground(new java.awt.Color(255, 255, 255));
        Btn_tieptuc.setText("THÊM MỚI");
        Btn_tieptuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_tieptuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_tieptucActionPerformed(evt);
            }
        });

        Btn_quaylai.setBackground(new java.awt.Color(0, 204, 204));
        Btn_quaylai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_quaylai.setForeground(new java.awt.Color(255, 255, 255));
        Btn_quaylai.setText("QUAY LẠI");
        Btn_quaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_quaylaiActionPerformed(evt);
            }
        });

        Txt_malop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_malopActionPerformed(evt);
            }
        });

        jLabel9.setText("Lớp:");

        Txt_Mamh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MamhActionPerformed(evt);
            }
        });

        jLabel10.setText("Mã môn học:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Btn_tieptuc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Txt_Mabd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(27, 27, 27)
                                                .addComponent(Txt_Tenhs, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(31, 31, 31)
                                                .addComponent(Txt_Mahs, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(38, 38, 38)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(51, 51, 51)
                                        .addComponent(Txt_hocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Txt_DiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Txt_Manv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(237, 237, 237)
                                        .addComponent(jLabel10)))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Txt_malop, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_Mamh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Txt_Mabd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Txt_DiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Txt_malop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Txt_Mahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_hocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Mamh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Txt_Tenhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(Txt_Manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_tieptuc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(Btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ThemActionPerformed
        // TODO add your handling code here:
        if(Txt_Mabd.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã học sinh cần thêm");
            Txt_Mahs.requestFocus();
            return;
        }
        if(Txt_Mahs.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên học sinh cần thêm");
            Txt_Tenhs.requestFocus();
            return;
        }
        if(Txt_Tenhs.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Lớp cần thêm");
            Txt_Tenhs.requestFocus();
            return;
        }
        if(Txt_DiemTB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_DiemTB.requestFocus();
            return;
        }
        if(Txt_hocluc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_hocluc.requestFocus();
            return;
        }
                        if(Txt_Manv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_Manv.requestFocus();
            return;
        }

        String mabd = Txt_Mabd.getText();
        String mahs = Txt_Mahs.getText();
        String malop = Txt_malop.getText();
        String mamh = Txt_malop.getText();
        String tenhs = Txt_Tenhs.getText();
        float diemtb = Float.parseFloat(Txt_DiemTB.getText());
        String hocluc = Txt_hocluc.getText();
        String Manv = Txt_Manv.getText();


        TTBangDiem hs = new TTBangDiem(mabd, mahs, tenhs, malop, mamh,  diemtb, hocluc, Manv);
        int smt = TTBangDiemBL.ThemBangDiem(hs);
        if(smt>0)
        JOptionPane.showMessageDialog(this, "Đã Thêm Thành Công Bảng điểm!");
        model = (DefaultTableModel)Tbl_Bangdiem.getModel();
        model.setRowCount(0);
        initStudent();
    }//GEN-LAST:event_Btn_ThemActionPerformed

    private void Btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SuaActionPerformed
        // TODO add your handling code here:

               if(Txt_Mabd.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã học sinh cần thêm");
            Txt_Mahs.requestFocus();
            return;
        }
        if(Txt_Mahs.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên học sinh cần thêm");
            Txt_Tenhs.requestFocus();
            return;
        }
        if(Txt_Tenhs.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Lớp cần thêm");
            Txt_Tenhs.requestFocus();
            return;
        }
        if(Txt_DiemTB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_DiemTB.requestFocus();
            return;
        }
        if(Txt_hocluc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_hocluc.requestFocus();
            return;
        }
                        if(Txt_Manv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_Manv.requestFocus();
            return;
        }

        String mabd = Txt_Mabd.getText();
        String mahs = Txt_Mahs.getText();
        String tenhs = Txt_Tenhs.getText();
        String malop = Txt_malop.getText();
        Float diemtb = Float.parseFloat(Txt_DiemTB.getText());
        String hocluc = Txt_hocluc.getText();
        String Manv = Txt_Manv.getText();
        
        TTBangDiemBL.SuaBangdiem(mabd, mahs, tenhs, malop,  diemtb, hocluc, Manv);
        JOptionPane.showMessageDialog(this, "Cập nhật thông tin Thành công");
        //refresh table
        model = (DefaultTableModel)Tbl_Bangdiem.getModel();
        model.setRowCount(0);
        initStudent();
    }//GEN-LAST:event_Btn_SuaActionPerformed

    private void Btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XoaActionPerformed
        // TODO add your handling code here:
        if(Txt_Mabd.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập Mã Bảng điểm cần xóa");
            Txt_Mabd.requestFocus();
            return;
        }

        int reply = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa Bảng điểm của học sinh " + Txt_Tenhs.getText()+ " ? ","Confirm",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION)
        {
            TTHOCSINHBL.XoaHocSinh(Txt_Mahs.getText());
            model.removeRow(Tbl_Bangdiem.getSelectedRow());
            Txt_Mabd.setText("");
            Txt_Mahs.setText("");
            Txt_Tenhs.setText("");
            Txt_DiemTB.setText("");
            Txt_hocluc.setText("");
            Txt_Manv.setText("");

            JOptionPane.showMessageDialog(rootPane, "Đã xóa thành công Bảng điểm");
        }
        initStudent();
    }//GEN-LAST:event_Btn_XoaActionPerformed

    private void Btn_tieptucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_tieptucActionPerformed
        // TODO add your handling code here:
            Txt_Mabd.requestFocus();
            Txt_Mahs.setText("");
            Txt_Tenhs.setText("");
            Txt_DiemTB.setText("");
            Txt_hocluc.setText("");
        Txt_Manv.setText("");
        ProcessCrt(false);
        this.Btn_Them.setEnabled(true);
    }//GEN-LAST:event_Btn_tieptucActionPerformed

    private void Btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_quaylaiActionPerformed
        // TODO add your handling code here:
        JFrameUngDungHeThong udht = new JFrameUngDungHeThong();
        udht.setTitle("QUẢN LÝ HỆ THỐNG");
        udht.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_quaylaiActionPerformed

    private void Tbl_BangdiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_BangdiemMouseClicked
        // TODO add your handling code here:
        Txt_Mabd.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(), 0)));
        Txt_Mahs.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),1)));
        Txt_Tenhs.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),2)));
        Txt_malop.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),3)));
        Txt_Mamh.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),4)));
        Txt_DiemTB.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),5)));
        Txt_hocluc.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),6)));
        Txt_Manv.setText(String.valueOf(model.getValueAt(Tbl_Bangdiem.getSelectedRow(),7)));
        ProcessCrt(false);
        this.Btn_Sua.setEnabled(true);
        this.Btn_Xoa.setEnabled(true);
        this.Txt_Mahs.setEditable(false);
    }//GEN-LAST:event_Tbl_BangdiemMouseClicked

    private void Txt_malopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_malopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_malopActionPerformed

    private void Txt_MamhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MamhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MamhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBangDiemHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBangDiemHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBangDiemHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBangDiemHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBangDiemHocSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Sua;
    private javax.swing.JButton Btn_Them;
    private javax.swing.JButton Btn_Xoa;
    private javax.swing.JButton Btn_quaylai;
    private javax.swing.JButton Btn_tieptuc;
    private javax.swing.JTable Tbl_Bangdiem;
    private javax.swing.JTextField Txt_DiemTB;
    private javax.swing.JTextField Txt_Mabd;
    private javax.swing.JTextField Txt_Mahs;
    private javax.swing.JTextField Txt_Mamh;
    private javax.swing.JTextField Txt_Manv;
    private javax.swing.JTextField Txt_Tenhs;
    private javax.swing.JTextField Txt_hocluc;
    private javax.swing.JTextField Txt_malop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
