/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.TTGiaoVienBL;
import DAL.TTGiaoVien;
import java.awt.Component;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thái Dương
 */
public class JFrameQuanLyGiaoVien extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyGV
     */
    public JFrameQuanLyGiaoVien() {
        initComponents();
        initStudent();
        ProcessCrt(false);
    }
DefaultTableModel model;
    void initStudent()
        {
            List<TTGiaoVien> listGV;
            listGV = TTGiaoVienBL.dsGiaoVien();
            if(listGV.size()>0)
        {
            model = (DefaultTableModel)Tbl_ThongTinGV.getModel();
            for(TTGiaoVien s: listGV) 
        {
            String phai="Nam";
                if(s.isbPhai()==false)
            {
                phai = "Nữ" ;
            }
                else
            {
                phai = "Nam" ;
            }
            model.addRow(new 
            Object[]{s.getStrMagv(),s.getStrTenGV(),s.getStrMamh(),phai,s.getDNgaysinh()});
        }
    } 
 }
    public void ProcessCrt(boolean b)
    {
        this.Btn_Them.setEnabled(b);
        this.Btn_Sua.setEnabled(b);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_magv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_TenGv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_ngaysinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_Mamh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_ThongTinGV = new javax.swing.JTable();
        Btn_Sua = new javax.swing.JButton();
        Btn_Them = new javax.swing.JButton();
        Btn_Moi = new javax.swing.JButton();
        Cmb_fale = new javax.swing.JComboBox<>();
        Btn_quaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("QUẢN LÝ THÔNG TIN GIÁO VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Mã giáo viên:");

        Txt_magv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Tên giáo viên:");

        Txt_TenGv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Ngày sinh:");

        Txt_ngaysinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Mã môn học:");

        Txt_Mamh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("DANH SÁCH THÔNG TIN GIÁO VIÊN");

        Tbl_ThongTinGV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tbl_ThongTinGV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giáo viên", "Tên giáo viên", "Mã môn học", "Giới tính", "Ngày sinh"
            }
        ));
        Tbl_ThongTinGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ThongTinGVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_ThongTinGV);

        Btn_Sua.setBackground(new java.awt.Color(255, 153, 51));
        Btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Sua.setText("SỬA");
        Btn_Sua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SuaActionPerformed(evt);
            }
        });

        Btn_Them.setBackground(new java.awt.Color(51, 255, 51));
        Btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Them.setText("THÊM");
        Btn_Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ThemActionPerformed(evt);
            }
        });

        Btn_Moi.setBackground(new java.awt.Color(255, 153, 153));
        Btn_Moi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Moi.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Moi.setText("THÊM MỚI");
        Btn_Moi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MoiActionPerformed(evt);
            }
        });

        Cmb_fale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cmb_fale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        Cmb_fale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Btn_quaylai.setBackground(new java.awt.Color(0, 204, 204));
        Btn_quaylai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_quaylai.setForeground(new java.awt.Color(255, 255, 255));
        Btn_quaylai.setText("QUAY LẠI");
        Btn_quaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_quaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Txt_magv, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Txt_TenGv)
                                                .addComponent(Txt_Mamh, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(141, 141, 141)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cmb_fale, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(199, 199, 199)))
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(Txt_magv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Cmb_fale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_TenGv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_Mamh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(Btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tbl_ThongTinGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ThongTinGVMouseClicked
        // TODO add your handling code here:
        Txt_magv.setText(String.valueOf(model.getValueAt(Tbl_ThongTinGV.getSelectedRow(), 0)));
        Txt_TenGv.setText(String.valueOf(model.getValueAt(Tbl_ThongTinGV.getSelectedRow(),1)));
        Cmb_fale.setSelectedItem(String.valueOf(model.getValueAt(Tbl_ThongTinGV.getSelectedRow(),3)));
        Txt_Mamh.setText(String.valueOf(model.getValueAt(Tbl_ThongTinGV.getSelectedRow(),2)));
        Txt_ngaysinh.setText(String.valueOf(model.getValueAt(Tbl_ThongTinGV.getSelectedRow(),4)));
        ProcessCrt(false);
        this.Btn_Sua.setEnabled(true);
    }//GEN-LAST:event_Tbl_ThongTinGVMouseClicked

    private void Btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SuaActionPerformed
        // TODO add your handling code here:
        if(Txt_magv.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Mã Giáo Viên không được để trống.");
            Txt_magv.requestFocus();
            return;
        }
        if(Txt_TenGv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên Giáo Viên không được để trống.");
            Txt_TenGv.requestFocus();
            return;
        }
        if(Txt_Mamh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã môn học không được để trống.");
            Txt_Mamh.requestFocus();
            return;
        }
        if(Txt_ngaysinh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ngày sinh của Giáo Viên không được để trống.");
            Txt_ngaysinh.requestFocus();
            return;
        }

        String magv = Txt_magv.getText();
        String tengv = Txt_TenGv.getText();
        String mamh = Txt_Mamh.getText();
        Date ngaysinh = Date.valueOf(Txt_ngaysinh.getText());
        int gt = Cmb_fale.getSelectedIndex();

        boolean phai = false;
        if(gt == 0) phai = true;
        else if(gt ==1) phai = false;

        TTGiaoVienBL.SuaGiaoVien(magv, tengv, phai, ngaysinh, mamh);
        JOptionPane.showMessageDialog(this, "Cập nhật thông tin Thành công");
        //refresh table
        model = (DefaultTableModel)Tbl_ThongTinGV.getModel();
        model.setRowCount(0);
        initStudent();
    }//GEN-LAST:event_Btn_SuaActionPerformed

    private void Btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ThemActionPerformed
        // TODO add your handling code here:
        if(Txt_magv.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã Giáo Viên cần thêm");
            Txt_magv.requestFocus();
            return;
        }
        if(Txt_TenGv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên Giáo Viêncần thêm");
            Txt_TenGv.requestFocus();
            return;
        }
        if(Txt_Mamh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã môn học cần thêm");
            Txt_Mamh.requestFocus();
            return;
        }
        if(Txt_ngaysinh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_ngaysinh.requestFocus();
            return;
        }

        String magv = Txt_magv.getText();
        String tengv = Txt_TenGv.getText();
        String mamh = Txt_Mamh.getText();
        Date ngaysinh = Date.valueOf(Txt_ngaysinh.getText());

        int gt = Cmb_fale.getSelectedIndex();
        boolean phai = false;
        if(gt == 0) phai = true;
        else if(gt ==1) phai = false;

        TTGiaoVien gv = new TTGiaoVien(magv, tengv, phai, ngaysinh, mamh);
        int smt = TTGiaoVienBL.ThemGiaoVien(gv);
        if(smt>0)
        JOptionPane.showMessageDialog(this, "Đã Thêm Giáo Viên Thành Công!");
        model = (DefaultTableModel)Tbl_ThongTinGV.getModel();
        model.setRowCount(0);
        initStudent();

    }//GEN-LAST:event_Btn_ThemActionPerformed

    private void Btn_MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MoiActionPerformed
        // TODO add your handling code here:
        Txt_magv.setText("");
        Txt_TenGv.setText("");
        Txt_Mamh.setText("");
        Txt_ngaysinh.setText("");
        Txt_magv.requestFocus();
        ProcessCrt(false);
        this.Btn_Them.setEnabled(true);
    }//GEN-LAST:event_Btn_MoiActionPerformed

    private void Btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_quaylaiActionPerformed
        // TODO add your handling code here:
        JFrameUngDungHeThong udht = new JFrameUngDungHeThong();
        udht.setTitle("QUẢN LÝ HỆ THỐNG");
        udht.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Btn_quaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameQuanLyGiaoVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Moi;
    private javax.swing.JButton Btn_Sua;
    private javax.swing.JButton Btn_Them;
    private javax.swing.JButton Btn_quaylai;
    private javax.swing.JComboBox<String> Cmb_fale;
    private javax.swing.JTable Tbl_ThongTinGV;
    private javax.swing.JTextField Txt_Mamh;
    private javax.swing.JTextField Txt_TenGv;
    private javax.swing.JTextField Txt_magv;
    private javax.swing.JTextField Txt_ngaysinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
