/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.TTNhanVienGiaoVuBL;
import DAL.TTHocSinh;
import DAL.TTNhanVienGiaoVu;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thái Dương
 */
public class JFrameQuanLyNVGV extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst =null;
    /**
     * Creates new form FormQuanLyNVGV
     */
    public JFrameQuanLyNVGV() {
        initComponents();
        initStudent();
        ProcessCrt(false);
    }
        ArrayList<TTNhanVienGiaoVu> arr =  new ArrayList<TTNhanVienGiaoVu>();
DefaultTableModel model;
        void initStudent()
        {
            List<TTNhanVienGiaoVu> listGV;
            listGV = TTNhanVienGiaoVuBL.dsgiaovu();
            if(listGV.size()>0)
        {
            model = (DefaultTableModel)Tbl_NhanVienGV.getModel();
            for(TTNhanVienGiaoVu s:listGV) 
        {
            String phai="Nam";
                if(s.isbPhai()==false)
            {
                phai = "Nữ" ;
            }
                else
            {
                phai = "Nam" ;
            }
            model.addRow(new 
            Object[]{s.getStrMaNV(),s.getStrTenNV(),phai,s.getdNgaySinh()});
        }
    } 
 }
        public void ProcessCrt(boolean b)
{
    this.Btn_Them.setEnabled(b);
    this.Btn_Sua.setEnabled(b);
    this.Btn_Xoa.setEnabled(b);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_TenNV = new javax.swing.JTextField();
        Txt_MaNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_NgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_NhanVienGV = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Btn_Sua = new javax.swing.JButton();
        Btn_Xoa = new javax.swing.JButton();
        Btn_moi = new javax.swing.JButton();
        Btn_Them = new javax.swing.JButton();
        Cmb_fale = new javax.swing.JComboBox<>();
        Btn_quaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("QUẢN LÝ THÔNG TIN NHÂN VIÊN GIÁO VỤ");

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Tên nhân viên:");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Ngày sinh:");

        Tbl_NhanVienGV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tbl_NhanVienGV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính", "Ngày sinh"
            }
        ));
        Tbl_NhanVienGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_NhanVienGVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_NhanVienGV);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("DANH SÁCH THÔNG TIN NHÂN VIÊN GIÁO VỤ");

        Btn_Sua.setBackground(new java.awt.Color(255, 204, 0));
        Btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Sua.setText("SỬA");
        Btn_Sua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SuaActionPerformed(evt);
            }
        });

        Btn_Xoa.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Xoa.setText("XÓA");
        Btn_Xoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XoaActionPerformed(evt);
            }
        });

        Btn_moi.setBackground(new java.awt.Color(255, 204, 204));
        Btn_moi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_moi.setForeground(new java.awt.Color(255, 255, 255));
        Btn_moi.setText("THÊM MỚI");
        Btn_moi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_moiActionPerformed(evt);
            }
        });

        Btn_Them.setBackground(new java.awt.Color(153, 255, 0));
        Btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Them.setText("THÊM");
        Btn_Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ThemActionPerformed(evt);
            }
        });

        Cmb_fale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        Btn_quaylai.setBackground(new java.awt.Color(0, 204, 204));
        Btn_quaylai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_quaylai.setForeground(new java.awt.Color(255, 255, 255));
        Btn_quaylai.setText("QUAY LẠI");
        Btn_quaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_quaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(Btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_moi)))
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Cmb_fale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Cmb_fale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_moi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(Btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1052, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tbl_NhanVienGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_NhanVienGVMouseClicked
        // TODO add your handling code here:
        Txt_MaNV.setText(String.valueOf(model.getValueAt(Tbl_NhanVienGV.getSelectedRow(), 0)));
        Txt_TenNV.setText(String.valueOf(model.getValueAt(Tbl_NhanVienGV.getSelectedRow(),1)));
        Cmb_fale.setSelectedItem(String.valueOf(model.getValueAt(Tbl_NhanVienGV.getSelectedRow(),2)));
        Txt_NgaySinh.setText(String.valueOf(model.getValueAt(Tbl_NhanVienGV.getSelectedRow(),3)));
        ProcessCrt(false);
        this.Btn_Sua.setEnabled(true);
        this.Btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_Tbl_NhanVienGVMouseClicked

    private void Btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SuaActionPerformed
        // TODO add your handling code here:
        if(Txt_MaNV.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã Nhân Viên cần thêm");
            Txt_MaNV.requestFocus();
            return;
        }
        if(Txt_TenNV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên Nhân Viên cần thêm");
            Txt_TenNV.requestFocus();
            return;
        }
        if(Txt_NgaySinh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_NgaySinh.requestFocus();
            return;
        }

        String manv = Txt_MaNV.getText();
        String hoten = Txt_TenNV.getText();
        Date ngaysinh = Date.valueOf(Txt_NgaySinh.getText());

        int gt = Cmb_fale.getSelectedIndex();
        boolean phai = false;
        if(gt == 0) phai = true;
        else if(gt ==1) phai = false;

        TTNhanVienGiaoVuBL.SuaNhanVien(manv, hoten, phai, ngaysinh);
        JOptionPane.showMessageDialog(this, "Cập nhật thông tin Thành công");

        model = (DefaultTableModel)Tbl_NhanVienGV.getModel();
        model.setRowCount(0);
        initStudent();

    }//GEN-LAST:event_Btn_SuaActionPerformed

    private void Btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XoaActionPerformed
        // TODO add your handling code here:
        if(Txt_MaNV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nhập Mã Nhân Viên cần xóa");
            Txt_MaNV.requestFocus();
            return;
        }

        int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa Nhân Viên " + Txt_TenNV.getText()+ " ? ","Confirm",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION)
        {

            TTNhanVienGiaoVuBL.XoaNhanVien(Txt_MaNV.getText());
            model.removeRow(Tbl_NhanVienGV.getSelectedRow());
            Txt_MaNV.setText("");
            Txt_TenNV.setText("");
            Txt_NgaySinh.setText("");

            JOptionPane.showMessageDialog(this, "Đã xóa thành công Nhân Viên ");
        }
    }//GEN-LAST:event_Btn_XoaActionPerformed

    private void Btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_moiActionPerformed
        // TODO add your handling code here:
        Txt_MaNV.setText("");
        Txt_TenNV.setText("");
        Txt_NgaySinh.setText("");
        Txt_MaNV.requestFocus();
        ProcessCrt(false);
        this.Btn_Them.setEnabled(true);
    }//GEN-LAST:event_Btn_moiActionPerformed

    private void Btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ThemActionPerformed
        // TODO add your handling code here:
        if(Txt_MaNV.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã Nhân Viên cần thêm");
            Txt_MaNV.requestFocus();
            return;
        }
        if(Txt_TenNV.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên Nhân Viên cần thêm");
            Txt_TenNV.requestFocus();
            return;
        }
        if(Txt_NgaySinh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ngày sinh cần thêm");
            Txt_NgaySinh.requestFocus();
            return;
        }

        String manv = Txt_MaNV.getText();
        String hoten = Txt_TenNV.getText();
        Date ngaysinh = Date.valueOf(Txt_NgaySinh.getText());

        int gt = Cmb_fale.getSelectedIndex();
        boolean phai = false;
        if(gt == 0) phai = true;
        else if(gt ==1) phai = false;

        TTNhanVienGiaoVu nv = new TTNhanVienGiaoVu(manv, hoten, phai, ngaysinh);
        int smt = TTNhanVienGiaoVuBL.ThemNV(nv);
        if(smt>0)
        JOptionPane.showMessageDialog(this, "Đã Thêm Học Sinh Thành Công!");
        model = (DefaultTableModel)Tbl_NhanVienGV.getModel();
        model.setRowCount(0);
        initStudent();
    }//GEN-LAST:event_Btn_ThemActionPerformed

    private void Btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_quaylaiActionPerformed
        // TODO add your handling code here:
        JFrameUngDungHeThong udht = new JFrameUngDungHeThong();
        udht.setTitle("QUẢN LÝ HỆ THỐNG");
        udht.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_quaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyNVGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyNVGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyNVGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLyNVGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameQuanLyNVGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Sua;
    private javax.swing.JButton Btn_Them;
    private javax.swing.JButton Btn_Xoa;
    private javax.swing.JButton Btn_moi;
    private javax.swing.JButton Btn_quaylai;
    private javax.swing.JComboBox<String> Cmb_fale;
    private javax.swing.JTable Tbl_NhanVienGV;
    private javax.swing.JTextField Txt_MaNV;
    private javax.swing.JTextField Txt_NgaySinh;
    private javax.swing.JTextField Txt_TenNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
