/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.QuanLyThongKe;
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Thái Dương
 */
public class ThongKeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeJFrame
     */
    public ThongKeJFrame() {
        initComponents();
            QuanLyThongKe qltk = new QuanLyThongKe();
//            showBarChart();
            qltk.setDateChart1(Jpn_view1);
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_root = new javax.swing.JPanel();
        Btn_quaylai = new javax.swing.JButton();
        Jpn_view1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpn_root.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_quaylai.setBackground(new java.awt.Color(0, 204, 204));
        Btn_quaylai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_quaylai.setForeground(new java.awt.Color(255, 255, 255));
        Btn_quaylai.setText("QUAY LẠI");
        Btn_quaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_quaylaiActionPerformed(evt);
            }
        });
        jpn_root.add(Btn_quaylai, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 100, 30));

        javax.swing.GroupLayout Jpn_view1Layout = new javax.swing.GroupLayout(Jpn_view1);
        Jpn_view1.setLayout(Jpn_view1Layout);
        Jpn_view1Layout.setHorizontalGroup(
            Jpn_view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
        );
        Jpn_view1Layout.setVerticalGroup(
            Jpn_view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jpn_root.add(Jpn_view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        getContentPane().add(jpn_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_quaylaiActionPerformed
        JFrameUngDungHeThong udht = new JFrameUngDungHeThong();
        udht.setTitle("QUẢN LÝ HỆ THỐNG");
        udht.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_quaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_quaylai;
    private javax.swing.JPanel Jpn_view1;
    private javax.swing.JPanel jpn_root;
    // End of variables declaration//GEN-END:variables
}
